# Gunakan image Node.js sebagai dasar
FROM node:14-slim

# Set direktori kerja
WORKDIR /usr/src/app

# Salin package.json dan package-lock.json
COPY package*.json ./

# Install dependensi aplikasi
RUN npm install

# Salin seluruh kode aplikasi
COPY . .

# Set environment PORT
ENV PORT 8080

# Expose port 8080
EXPOSE 8080

# Eksekusi perintah untuk menjalankan aplikasi
CMD ["node", "index.js"]
